[2024-03-18T06:17:25.071+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sftp_sync.remove_tmp_files manual__2024-03-18T06:16:47.801798+00:00 [queued]>
[2024-03-18T06:17:25.118+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sftp_sync.remove_tmp_files manual__2024-03-18T06:16:47.801798+00:00 [queued]>
[2024-03-18T06:17:25.119+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-03-18T06:17:25.172+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): remove_tmp_files> on 2024-03-18 06:16:47.801798+00:00
[2024-03-18T06:17:25.346+0000] {standard_task_runner.py:60} INFO - Started process 210 to run task
[2024-03-18T06:17:25.434+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'sftp_sync', 'remove_tmp_files', 'manual__2024-03-18T06:16:47.801798+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/sftp_sync_between_source_and_target.py', '--cfg-path', '/tmp/tmpbt7oxe_y']
[2024-03-18T06:17:25.448+0000] {standard_task_runner.py:88} INFO - Job 70: Subtask remove_tmp_files
[2024-03-18T06:17:26.251+0000] {task_command.py:423} INFO - Running <TaskInstance: sftp_sync.remove_tmp_files manual__2024-03-18T06:16:47.801798+00:00 [running]> on host fa05d1b87173
[2024-03-18T06:17:26.941+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sftp_sync' AIRFLOW_CTX_TASK_ID='remove_tmp_files' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T06:16:47.801798+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-18T06:16:47.801798+00:00'
[2024-03-18T06:17:27.008+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-18T06:17:27.042+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'rm -rf /tmp/*']
[2024-03-18T06:17:27.337+0000] {subprocess.py:86} INFO - Output:
[2024-03-18T06:17:27.472+0000] {subprocess.py:93} INFO - rm: cannot remove '/tmp/tmpv3xu9816': Operation not permitted
[2024-03-18T06:17:27.474+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-18T06:17:27.708+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-18T06:17:27.760+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=sftp_sync, task_id=remove_tmp_files, execution_date=20240318T061647, start_date=20240318T061725, end_date=20240318T061727
[2024-03-18T06:17:27.839+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 70 for task remove_tmp_files (Bash command failed. The command returned a non-zero exit code 1.; 210)
[2024-03-18T06:17:27.961+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-18T06:17:28.402+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
